# config/otel-collector.yml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024
    send_batch_max_size: 2048
  
  resource:
    attributes:
      - key: environment
        value: development
        action: upsert
      - key: service.namespace
        value: go-microservice
        action: upsert

  memory_limiter:
    limit_mib: 512
    check_interval: 1s

exporters:
  # Export metrics ke Prometheus
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      environment: development
    
  # Export traces ke Tempo
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
    sending_queue:
      num_consumers: 4
      queue_size: 100
    retry_on_failure:
      enabled: true
      initial_interval: 10ms
      max_interval: 60s
      max_elapsed_time: 10m

  # Export logs ke Loki (via OTLP)
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  # Debug logging
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlp/tempo, debug]
    
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheus, debug]
    
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [loki, debug]

  extensions: []