# config/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'go-app'
    static_configs:
      - targets: ['go-app:8080']
    metrics_path: '/metrics'

  - job_name: 'fluent-bit'
    static_configs:
      - targets: ['fluent-bit:2020']